AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PetStoreAPI Sample
Globals:
  Function:
    Runtime: python3.7
    Layers:
    - Ref: PetStoreAPILayer
    Environment:
      Variables:
        PETS_TABLE:
          Ref: PetsTable
Resources:
  PetsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreatePet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handler
      CodeUri: s3://petstore-api-jumpyoshim/e81848b9a12b9edd5276f76b94b07a82
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: PetsTable
  PetStoreAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://petstore-api-jumpyoshim/c61f21a22601bb7ad75ec39ccf2e10a2
  PetStoreAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Lambda Layer for PetStoreAPI
      ContentUri: s3://petstore-api-jumpyoshim/de69e8e0cb3b3ecc0aa819f97d259a1d
  LambdaPermissionCreatePet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: CreatePet
      Principal: apigateway.amazonaws.com
  CreatePetLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${CreatePet}
      RetentionInDays: 14
Outputs:
  ApiURL:
    Description: API endpoint URL for PetStoreAPI
    Value:
      Fn::Sub: https://${PetStoreAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/
