openapi: "3.0.2"
info:
  title: PetStore
  license:
    name: MIT
  version: "1.0"
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    post:
      summary: Create a pet
      operationId: createPet
      tags:
        - pets
      responses:
        "201":
          description: Created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePet.Arn}/invocations
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        name:
          type: string
          minLength: 1
          maxLength: 50
        tags:
          type: array
          minItems: 1
          maxItems: 10
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                minimum: 0
              name:
                type: string
                minLength: 1
                maxLength: 50
            required:
              - id
              - name
