AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: PetStoreAPI Sample
Globals:
  Function:
    Runtime: python3.7
    Layers:
      - !Ref PetStoreAPILayer
    Environment:
      Variables:
        PETS_TABLE: !Ref PetsTable
Resources:
  PetsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreatePet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handler
      CodeUri: src/handlers/pets
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PetsTable
  PetStoreAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml
  PetStoreAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Lambda Layer for PetStoreAPI
      ContentUri: layer
  LambdaPermissionCreatePet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreatePet
      Principal: apigateway.amazonaws.com
  CreatePetLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreatePet}
      RetentionInDays: 14
Outputs:
  ApiURL:
    Description: API endpoint URL for PetStoreAPI
    Value: !Sub "https://${PetStoreAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
